name: 'rpmbuild'
description: 'Build RPM from spec file and source code'
author: 'Naveenraj M'

inputs: 
  specFile:
    description: 'path to the spec file'
    required: true
    default: '.'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
